services:
    ticket_provider:
        class: Kijho\HelpDeskBundle\Services\TicketProvider
        arguments: [@service_container, @doctrine.orm.entity_manager]
        
    #servicio para pasarle el container al formulario de tickets
    help_desk.client.form.type.ticket:
        class: Kijho\HelpDeskBundle\Form\Client\TicketType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }
    
    #servicio para pasarle el container al formulario de comentarios en tickets
    help_desk.form.type.ticket_comment:
        class: Kijho\HelpDeskBundle\Form\Client\TicketCommentType
        arguments:
            - "@service_container"
        tags:
            - { name: form.type }