services:
    ticket_provider:
        class: Kijho\HelpDeskBundle\Services\TicketProvider
        arguments: [@service_container, @doctrine.orm.entity_manager]
        
    help_desk_email_manager:
        class: Kijho\HelpDeskBundle\Services\EmailManager
        arguments: 
            requestStack:   "@request_stack"
            container:      "@service_container"
            entityManager:  "@doctrine.orm.entity_manager"
