services:
    ticket_provider:
        class: Kijho\HelpDeskBundle\Services\TicketProvider
        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
        
    help_desk_email_manager:
        class: Kijho\HelpDeskBundle\Services\EmailManager
        arguments: ["@request_stack","@service_container","@doctrine.orm.entity_manager"]

