# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    
    providers:
        help_desk_provider:
            entity: { class: Kijho\HelpDeskBundle\Entity\User, property: email }
            
    encoders:
        help_desk:
            class: Kijho\HelpDeskBundle\Entity\User
            algorithm: plaintext
            
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        help_desk_client:
            pattern:    '^/*'
            form_login:
                check_path: help_desk_login_check
                login_path: help_desk_login
                default_target_path: help_desk_redirect
                always_use_default_target_path: true
            logout:
                path:   help_desk_logout
                target: help_desk_login
            anonymous: ~
            provider: help_desk_provider
            
        help_desk_operator:
            pattern:    '^/*'
            form_login:
                check_path: help_desk_login_check
                login_path: help_desk_login
                default_target_path: help_desk_redirect
                always_use_default_target_path: true
            logout:
                path:   help_desk_logout
                target: help_desk_login
            anonymous: ~
            provider: help_desk_provider

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/redirect', roles: [ROLE_CLIENT, ROLE_OPERATOR] }
        - { path: '^/client/*', roles: ROLE_CLIENT }
        - { path: '^/operator/*', roles: ROLE_OPERATOR }

