help_desk_client_tickets:
    path:     /tickets/{status}
    defaults: { _controller: HelpDeskBundle:Client:myTickets }
    
help_desk_client_tickets_new:
    path:     /newTicket
    defaults: { _controller: HelpDeskBundle:Client:newSupportTicket }
    
help_desk_client_tickets_view:
    path:     /tickets/{id}/view
    defaults: { _controller: HelpDeskBundle:Client:viewTicket }